


(define (problem cube-11-6)
(:domain cube)
(:objects p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 )
(:init
(x-above p2 p1)
(x-above p3 p2)
(x-above p4 p3)
(x-above p5 p4)
(x-above p6 p5)
(x-above p7 p6)
(x-above p8 p7)
(x-above p9 p8)
(x-above p10 p9)
(x-above p11 p10)
(y-above p2 p1)
(y-above p3 p2)
(y-above p4 p3)
(y-above p5 p4)
(y-above p6 p5)
(y-above p7 p6)
(y-above p8 p7)
(y-above p9 p8)
(y-above p10 p9)
(y-above p11 p10)
(z-above p2 p1)
(z-above p3 p2)
(z-above p4 p3)
(z-above p5 p4)
(z-above p6 p5)
(z-above p7 p6)
(z-above p8 p7)
(z-above p9 p8)
(z-above p10 p9)
(z-above p11 p10)
(unknown (x-pos p1))
(unknown (x-pos p2))
(unknown (x-pos p3))
(unknown (x-pos p4))
(unknown (x-pos p5))
(unknown (x-pos p6))
(unknown (x-pos p7))
(unknown (x-pos p8))
(unknown (x-pos p9))
(unknown (x-pos p10))
(unknown (x-pos p11))
(oneof
(x-pos p1)
(x-pos p2)
(x-pos p3)
(x-pos p4)
(x-pos p5)
(x-pos p6)
(x-pos p7)
(x-pos p8)
(x-pos p9)
(x-pos p10)
(x-pos p11)
)
(unknown (y-pos p1))
(unknown (y-pos p2))
(unknown (y-pos p3))
(unknown (y-pos p4))
(unknown (y-pos p5))
(unknown (y-pos p6))
(unknown (y-pos p7))
(unknown (y-pos p8))
(unknown (y-pos p9))
(unknown (y-pos p10))
(unknown (y-pos p11))
(oneof
(y-pos p1)
(y-pos p2)
(y-pos p3)
(y-pos p4)
(y-pos p5)
(y-pos p6)
(y-pos p7)
(y-pos p8)
(y-pos p9)
(y-pos p10)
(y-pos p11)
)
(unknown (z-pos p1))
(unknown (z-pos p2))
(unknown (z-pos p3))
(unknown (z-pos p4))
(unknown (z-pos p5))
(unknown (z-pos p6))
(unknown (z-pos p7))
(unknown (z-pos p8))
(unknown (z-pos p9))
(unknown (z-pos p10))
(unknown (z-pos p11))
(oneof
(z-pos p1)
(z-pos p2)
(z-pos p3)
(z-pos p4)
(z-pos p5)
(z-pos p6)
(z-pos p7)
(z-pos p8)
(z-pos p9)
(z-pos p10)
(z-pos p11)
)
)
(:goal
(and
(x-pos p6)
(y-pos p6)
(z-pos p6)
)
)
)


