


(define (problem safe-30)
(:domain safe)
(:objects c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 c21 c22 c23 c24 c25 c26 c27 c28 c29 c30 )
(:init
(unknown (right-combination c1))
(unknown (right-combination c2))
(unknown (right-combination c3))
(unknown (right-combination c4))
(unknown (right-combination c5))
(unknown (right-combination c6))
(unknown (right-combination c7))
(unknown (right-combination c8))
(unknown (right-combination c9))
(unknown (right-combination c10))
(unknown (right-combination c11))
(unknown (right-combination c12))
(unknown (right-combination c13))
(unknown (right-combination c14))
(unknown (right-combination c15))
(unknown (right-combination c16))
(unknown (right-combination c17))
(unknown (right-combination c18))
(unknown (right-combination c19))
(unknown (right-combination c20))
(unknown (right-combination c21))
(unknown (right-combination c22))
(unknown (right-combination c23))
(unknown (right-combination c24))
(unknown (right-combination c25))
(unknown (right-combination c26))
(unknown (right-combination c27))
(unknown (right-combination c28))
(unknown (right-combination c29))
(unknown (right-combination c30))
(oneof
(right-combination c1)
(right-combination c2)
(right-combination c3)
(right-combination c4)
(right-combination c5)
(right-combination c6)
(right-combination c7)
(right-combination c8)
(right-combination c9)
(right-combination c10)
(right-combination c11)
(right-combination c12)
(right-combination c13)
(right-combination c14)
(right-combination c15)
(right-combination c16)
(right-combination c17)
(right-combination c18)
(right-combination c19)
(right-combination c20)
(right-combination c21)
(right-combination c22)
(right-combination c23)
(right-combination c24)
(right-combination c25)
(right-combination c26)
(right-combination c27)
(right-combination c28)
(right-combination c29)
(right-combination c30)
)
)
(:goal
(and
(safe-open)
)
)
)


