


(define (problem safe-70)
(:domain safe)
(:objects c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 c21 c22 c23 c24 c25 c26 c27 c28 c29 c30 c31 c32 c33 c34 c35 c36 c37 c38 c39 c40 c41 c42 c43 c44 c45 c46 c47 c48 c49 c50 c51 c52 c53 c54 c55 c56 c57 c58 c59 c60 c61 c62 c63 c64 c65 c66 c67 c68 c69 c70 )
(:init
(unknown (right-combination c1))
(unknown (right-combination c2))
(unknown (right-combination c3))
(unknown (right-combination c4))
(unknown (right-combination c5))
(unknown (right-combination c6))
(unknown (right-combination c7))
(unknown (right-combination c8))
(unknown (right-combination c9))
(unknown (right-combination c10))
(unknown (right-combination c11))
(unknown (right-combination c12))
(unknown (right-combination c13))
(unknown (right-combination c14))
(unknown (right-combination c15))
(unknown (right-combination c16))
(unknown (right-combination c17))
(unknown (right-combination c18))
(unknown (right-combination c19))
(unknown (right-combination c20))
(unknown (right-combination c21))
(unknown (right-combination c22))
(unknown (right-combination c23))
(unknown (right-combination c24))
(unknown (right-combination c25))
(unknown (right-combination c26))
(unknown (right-combination c27))
(unknown (right-combination c28))
(unknown (right-combination c29))
(unknown (right-combination c30))
(unknown (right-combination c31))
(unknown (right-combination c32))
(unknown (right-combination c33))
(unknown (right-combination c34))
(unknown (right-combination c35))
(unknown (right-combination c36))
(unknown (right-combination c37))
(unknown (right-combination c38))
(unknown (right-combination c39))
(unknown (right-combination c40))
(unknown (right-combination c41))
(unknown (right-combination c42))
(unknown (right-combination c43))
(unknown (right-combination c44))
(unknown (right-combination c45))
(unknown (right-combination c46))
(unknown (right-combination c47))
(unknown (right-combination c48))
(unknown (right-combination c49))
(unknown (right-combination c50))
(unknown (right-combination c51))
(unknown (right-combination c52))
(unknown (right-combination c53))
(unknown (right-combination c54))
(unknown (right-combination c55))
(unknown (right-combination c56))
(unknown (right-combination c57))
(unknown (right-combination c58))
(unknown (right-combination c59))
(unknown (right-combination c60))
(unknown (right-combination c61))
(unknown (right-combination c62))
(unknown (right-combination c63))
(unknown (right-combination c64))
(unknown (right-combination c65))
(unknown (right-combination c66))
(unknown (right-combination c67))
(unknown (right-combination c68))
(unknown (right-combination c69))
(unknown (right-combination c70))
(oneof
(right-combination c1)
(right-combination c2)
(right-combination c3)
(right-combination c4)
(right-combination c5)
(right-combination c6)
(right-combination c7)
(right-combination c8)
(right-combination c9)
(right-combination c10)
(right-combination c11)
(right-combination c12)
(right-combination c13)
(right-combination c14)
(right-combination c15)
(right-combination c16)
(right-combination c17)
(right-combination c18)
(right-combination c19)
(right-combination c20)
(right-combination c21)
(right-combination c22)
(right-combination c23)
(right-combination c24)
(right-combination c25)
(right-combination c26)
(right-combination c27)
(right-combination c28)
(right-combination c29)
(right-combination c30)
(right-combination c31)
(right-combination c32)
(right-combination c33)
(right-combination c34)
(right-combination c35)
(right-combination c36)
(right-combination c37)
(right-combination c38)
(right-combination c39)
(right-combination c40)
(right-combination c41)
(right-combination c42)
(right-combination c43)
(right-combination c44)
(right-combination c45)
(right-combination c46)
(right-combination c47)
(right-combination c48)
(right-combination c49)
(right-combination c50)
(right-combination c51)
(right-combination c52)
(right-combination c53)
(right-combination c54)
(right-combination c55)
(right-combination c56)
(right-combination c57)
(right-combination c58)
(right-combination c59)
(right-combination c60)
(right-combination c61)
(right-combination c62)
(right-combination c63)
(right-combination c64)
(right-combination c65)
(right-combination c66)
(right-combination c67)
(right-combination c68)
(right-combination c69)
(right-combination c70)
)
)
(:goal
(and
(safe-open)
)
)
)


